# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govforge < Formula
  desc "GovForge CLI — governance for AI coding agents"
  homepage "https://govforge.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ericvaillancourt/govforge/releases/download/v0.1.0/gf_0.1.0_darwin_x86_64.tar.gz"
      sha256 "f20b04e2db0d48c7ea21dee32f3461971fcd252a72b55e45c1486b72ef55b081"

      define_method(:install) do
        bin.install "gf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ericvaillancourt/govforge/releases/download/v0.1.0/gf_0.1.0_darwin_arm64.tar.gz"
      sha256 "fa531f95c3b775df3139bcce2379d17182764b0f9a21c9ff45a3d1179b10e8b5"

      define_method(:install) do
        bin.install "gf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericvaillancourt/govforge/releases/download/v0.1.0/gf_0.1.0_linux_x86_64.tar.gz"
      sha256 "61f3f2a902e020e9ee2801cc17ae1029c8a2cb9040fadf12b042a6fbe90e1f9a"
      define_method(:install) do
        bin.install "gf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericvaillancourt/govforge/releases/download/v0.1.0/gf_0.1.0_linux_arm64.tar.gz"
      sha256 "f51fc4b65b9abc6f4ce1b57597f053417f9634958e55a284adcd3b946ab18e3c"
      define_method(:install) do
        bin.install "gf"
      end
    end
  end

  test do
    system "#{bin}/gf", "version"
  end
end
