# This file was generated by GoReleaser. DO NOT EDIT.
cask "govforge" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "da0aa70c88f72cb4f5fa55236091dcfa535bf49537db80ebaf88881f1c401de6"
      url "https://github.com/ericvaillancourt/govforge/releases/download/v#{version}/gf_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fec77adb7e8681b833cfe73da75dfebc9cacd68d60221b5f6c373f1ffbcb5a75"
      url "https://github.com/ericvaillancourt/govforge/releases/download/v#{version}/gf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "617ea63130524aef849210370c7684815ac4c555d0aefb35bb49fcee5f2b2580"
      url "https://github.com/ericvaillancourt/govforge/releases/download/v#{version}/gf_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d776938bae0edc1e14ee2ee0a8729fb2aeb8ab4956c1bf27a03371d94ac6452b"
      url "https://github.com/ericvaillancourt/govforge/releases/download/v#{version}/gf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "govforge"
  desc "GovForge CLI — governance for AI coding agents"
  homepage "https://govforge.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gf"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system "xattr", "-d", "com.apple.quarantine", "#{staged_path}/gf"
    end
  end

  # No zap stanza required

end
